avg_num_neighbor_head: mp_pbe
device: cuda
multi_processed_test: True
heads: 
    mp_pbe:
        train_file: /lustre/fsn1/projects/rech/gax/commun/mace_mp_data/train 
        valid_file: /lustre/fsn1/projects/rech/gax/commun/mace_mp_data/valid 
        E0s: /lustre/fsn1/projects/rech/gax/unh55hx/data/e0s.json
        config_type_weights:
            Default: 1.0
        avg_num_neighbors: 61.93332947422808
        mean: -4.467034047769351
        std: 0.7381264819243595
#test_file: /lustre/fsn1/projects/rech/gax/unh55hx/data/multihead_datasets/test/spice
#statistics_file: /lustre/fsn1/projects/rech/gax/unh55hx/data/statistics.json 
