avg_num_neighbor_head: mp_pbe
device: cuda
multi_processed_test: True
heads: 
    mp_pbe:
        train_file: /lustre/fsn1/projects/rech/gax/unh55hx/data/multihead_datasets/train/MatProj
        valid_file: /lustre/fsn1/projects/rech/gax/unh55hx/data/multihead_datasets/valid/MatProj
        E0s: /lustre/fsn1/projects/rech/gax/unh55hx/data/e0s.json
        config_type_weights:
            Default: 1.0
        avg_num_neighbors: 99.8546949928121
        mean: -4.473512642887651
        std: 0.7452662891707729
#test_file: /lustre/fsn1/projects/rech/gax/unh55hx/data/multihead_datasets/test/spice
#statistics_file: /lustre/fsn1/projects/rech/gax/unh55hx/data/statistics.json 
