avg_num_neighbor_head: matpes_pbe
device: cuda
multi_processed_test: True
heads: 
    matpes_pbe:
        train_file: /lustre/fswork/projects/rech/gax/usj67fz/mace-matpes/matpes-pbe-filtered.xyz
        config_type_weights:
            Default: 1.0
        avg_num_neighbors: 61.9649349317854
        mean: 0.1634233391135065
        std: 0.7735790334431056
        valid_fraction: 0.1
        energy_key: "energy"
        forces_key: "forces"
        stress_key: "stress"
        statistics_file: "/lustre/fswork/projects/rech/gax/usj67fz/mace-matpes/matpes-pbe-statistics.json"
