from typing import Callable, Dict, Optional, Type

import torch

from .blocks import (
    AgnosticNonlinearInteractionBlock,
    AgnosticResidualNonlinearInteractionBlock,
    AtomicEnergiesBlock,
    EquivariantProductBasisBlock,
    EquivariantCPRingBasisBlock,
    EquivariantLowOrderProductBasisBlock,
    EquivariantProductBasisDensityAttnBlock,
    InteractionBlock,
    LinearDipoleReadoutBlock,
    LinearNodeEmbeddingBlock,
    LinearReadoutBlock,
    NonLinearDipoleReadoutBlock,
    NonLinearReadoutBlock,
    RadialEmbeddingBlock,
    RealAgnosticAttResidualInteractionBlock,
    RealAgnosticInteractionBlock,
    RealAgnosticResidualInteractionBlock,
    RealAgnosticInteractionGateBlock,
    RealAgnosticResidualInteractionGateBlock,
    RealAgnosticSimplifiedDensityHeadInteractionBlock,
    RealAgnosticSimplifiedDensityInteractionBlock,
    RealAgnosticSimplifiedDensityInteractionBlockSCv2,
    RealAgnosticSimplifiedDensityResidualHeadInteractionBlock,
    RealAgnosticSimplifiedDensityResidualInteractionBlock,
    RealAgnosticDensityNormalizedInteractionGateBlock,
    RealAgnosticDensityNormalizedNoScaleInteractionGateBlock,
    RealAgnosticDensityInjuctedInteractionGateBlock,
    RealAgnosticDensityInjuctedNoScaleInteractionGateBlock,
    RealAgnosticDensityInjuctedNoScaleNoBiasInteractionGateBlock,
    RealAgnosticDensityInjuctedNodeAttrAttendInteractionGateBlock,
    RealAgnosticDensityInjuctedNodeAttrAttendResidualInteractionGateBlock,
    RealAgnosticDensityInjuctedNoScaleNoBiasResidualInteractionGateBlock,
    RealAgnosticDensityInjuctedNoScaleResidualInteractionGateBlock,
    RealAgnosticDensityInjuctUnnormalizedNoScaleInteractionGateBlock,
    RealAgnosticSimplifiedDensityInteractionBlockSC,
    RealAgnosticSimplifiedDensityInteractionBlockSCv2,
    RealAgnosticSimplifiedDensityHeadInteractionBlock,
    RealAgnosticSimplifiedDensityResidualHeadInteractionBlock,
    RealAgnosticDensityNonSymmetricInteractionBlock,
    RealAgnosticDensityNonSymmetricResidualInteractionBlock,
    RealAgnosticSimplifiedDensityAttentionInteractionBlock,
    RealAgnosticSimplifiedDensityAttentionResidualInteractionBlock,
    RealAgnosticSimplifiedDensityMultiAttentionInteractionBlock,
    RealAgnosticSimplifiedDensityMultiAttentionResidualInteractionBlock,
    RealAgnosticSimplifiedDensityMultiSCAttentionInteractionBlock,
    RealAgnosticSimplifiedDensityMultiSCAttentionResidualInteractionBlock,
    RealAgnosticSimplifiedDensityCutoffMultiSCAttentionInteractionBlock,
    RealAgnosticSimplifiedDensityCutoffMultiSCAttentionResidualInteractionBlock,
    RealAgnosticDensityNFInteractionBlock,
    RealAgnosticDensityNFResidualInteractionBlock,
    RealAgnosticDensityResidualInteractionBlock,
    RealAgnosticDensityInteractionBlock,
        
    #RealAgnosticDensityNormalizedResidualInteractionGateBlock,
    ResidualElementDependentInteractionBlock,
    ScaleShiftBlock,
)

from .new_blocks import (
RealAgnosticLongRangeInteractionBlock,
RealAgnosticLongRangeResidualInteractionBlock,
)

from .loss import (
    DipoleSingleLoss,
    UniversalLoss,
    WeightedEnergyForcesDipoleLoss,
    WeightedEnergyForcesLoss,
    WeightedEnergyForcesStressLoss,
    WeightedEnergyForcesVirialsLoss,
    WeightedForcesLoss,
    WeightedHuberEnergyForcesStressLoss,
    OMat24Loss,
    DDP_weighted_MAE_all,
    DDP_weighted_MAE_peratomE,
)
from .models import (
    MACE,
    AtomicDipolesMACE,
    BOTNet,
    EnergyDipolesMACE,
    ScaleShiftBOTNet,
    ScaleShiftMACE,
    ScaleShiftLRMACE,

)
from .radial import BesselBasis, GaussianBasis, PolynomialCutoff, ZBLBasis
from .symmetric_contraction import SymmetricContraction
from .utils import (
    compute_avg_num_neighbors,
    compute_avg_num_neighbors_per_elem,
    raw_num_neighbors_per_elem,
    compute_fixed_charge_dipole,
    compute_mean_rms_energy_forces,
    compute_mean_std_atomic_inter_energy,
    compute_rms_dipoles,
    compute_statistics,
)

interaction_classes: Dict[str, Type[InteractionBlock]] = {
    "AgnosticNonlinearInteractionBlock": AgnosticNonlinearInteractionBlock,
    "ResidualElementDependentInteractionBlock": ResidualElementDependentInteractionBlock,
    "AgnosticResidualNonlinearInteractionBlock": AgnosticResidualNonlinearInteractionBlock,
    #"RealAgnosticResidualInteractionBlock": RealAgnosticResidualInteractionBlock,
    "RealAgnosticResidualInteractionBlock": RealAgnosticResidualInteractionGateBlock,
    "RealAgnosticAttResidualInteractionBlock": RealAgnosticAttResidualInteractionBlock,
    #"RealAgnosticInteractionBlock": RealAgnosticInteractionBlock,
    "RealAgnosticInteractionBlock": RealAgnosticInteractionGateBlock,
    "RealAgnosticDensityNormalizedInteractionBlock": RealAgnosticDensityNormalizedInteractionGateBlock,
    "RealAgnosticDensityInjuctedInteractionBlock": RealAgnosticDensityInjuctedInteractionGateBlock,
    "RealAgnosticDensityInjuctedNoScaleInteractionBlock": RealAgnosticDensityInjuctedNoScaleInteractionGateBlock,
    "RealAgnosticDensityInjuctedNoScaleNoBiasInteractionBlock": RealAgnosticDensityInjuctedNoScaleNoBiasInteractionGateBlock,
    "RealAgnosticDensityInjuctedNodeAttrAttendInteractionBlock": RealAgnosticDensityInjuctedNodeAttrAttendInteractionGateBlock,
    "RealAgnosticDensityInjuctedNodeAttrAttendResidualInteractionBlock": RealAgnosticDensityInjuctedNodeAttrAttendResidualInteractionGateBlock,
    "RealAgnosticDensityNormalizedNoScaleInteractionBlock": RealAgnosticDensityNormalizedNoScaleInteractionGateBlock,
    "RealAgnosticDensityInjuctedNoScaleNoBiasResidualInteractionBlock": RealAgnosticDensityInjuctedNoScaleNoBiasResidualInteractionGateBlock,
    "RealAgnosticDensityInjuctedNoScaleResidualInteractionBlock": RealAgnosticDensityInjuctedNoScaleResidualInteractionGateBlock,
    "RealAgnosticDensityInjuctUnnormalizedNoScaleInteractionBlock": RealAgnosticDensityInjuctUnnormalizedNoScaleInteractionGateBlock,
    "RASimpleDensityIntBlock": RealAgnosticSimplifiedDensityInteractionBlock,
    "RASimpleDensityAttnIntBlock": RealAgnosticSimplifiedDensityAttentionInteractionBlock,
    "RASimpleDensityAttnResidualIntBlock": RealAgnosticSimplifiedDensityAttentionResidualInteractionBlock,
    "RASimpleDensityMultiAttnIntBlock": RealAgnosticSimplifiedDensityMultiAttentionInteractionBlock,
    "RASimpleDensityMultiAttnResidualIntBlock": RealAgnosticSimplifiedDensityMultiAttentionResidualInteractionBlock,

    "RASimpleDensityMultiSCAttnIntBlock": RealAgnosticSimplifiedDensityMultiSCAttentionInteractionBlock,
    "RASimpleDensityMultiSCAttnResidualIntBlock": RealAgnosticSimplifiedDensityMultiSCAttentionResidualInteractionBlock,
    "RASimpleDensityCutoffMultiSCAttnIntBlock": RealAgnosticSimplifiedDensityCutoffMultiSCAttentionInteractionBlock,
    "RASimpleDensityCutoffMultiSCAttnResidualIntBlock": RealAgnosticSimplifiedDensityCutoffMultiSCAttentionResidualInteractionBlock,
    "RASimpleDensityResidualIntBlock": RealAgnosticSimplifiedDensityResidualInteractionBlock,
    "RASimpleDensityIntBlockSC": RealAgnosticSimplifiedDensityInteractionBlockSC,
    "RASimpleDensityIntBlockSCv2": RealAgnosticSimplifiedDensityInteractionBlockSCv2,
    "RASimpleDensityHeadIntBlock": RealAgnosticSimplifiedDensityHeadInteractionBlock,
    "RASimpleDensityResidualHeadIntBlock": RealAgnosticSimplifiedDensityResidualHeadInteractionBlock,
    "RASimpleDensityNSIntBlock": RealAgnosticDensityNonSymmetricInteractionBlock,
    "RASimpleDensityResidualNSIntBlock": RealAgnosticDensityNonSymmetricResidualInteractionBlock,
    "RADensityNFIntBlock": RealAgnosticDensityNFInteractionBlock,
    "RADensityNFResidualIntBlock": RealAgnosticDensityNFResidualInteractionBlock,
    "RealAgnosticDensityResidualInteractionBlock": RealAgnosticDensityResidualInteractionBlock,
    "RealAgnosticDensityInteractionBlock": RealAgnosticDensityInteractionBlock,
    "RALRIntBlock":RealAgnosticLongRangeInteractionBlock,
    "RALRResIntBlock":RealAgnosticLongRangeResidualInteractionBlock,
}

contraction_classes: Dict[str, torch.nn.Module] = {
    "EquivariantProductBasisBlock": EquivariantProductBasisBlock,
    "EquivariantCPRingBasisBlock": EquivariantCPRingBasisBlock,
    "EquivariantLowOrderProductBasisBlock": EquivariantLowOrderProductBasisBlock,
    "EquivariantProductBasisDensityAttnBlock": EquivariantProductBasisDensityAttnBlock
}

scaling_classes: Dict[str, Callable] = {
    "std_scaling": compute_mean_std_atomic_inter_energy,
    "rms_forces_scaling": compute_mean_rms_energy_forces,
    "rms_dipoles_scaling": compute_rms_dipoles,
}

gate_dict: Dict[str, Optional[Callable]] = {
    "abs": torch.abs,
    "tanh": torch.tanh,
    "silu": torch.nn.functional.silu,
    "elu": torch.nn.functional.elu,
    "softplus": torch.nn.functional.softplus,
    "gelu": torch.nn.functional.gelu,
    "None": None,
}

__all__ = [
    "AtomicEnergiesBlock",
    "RadialEmbeddingBlock",
    "ZBLBasis",
    "LinearNodeEmbeddingBlock",
    "LinearReadoutBlock",
    "EquivariantProductBasisBlock",
    "EquivariantCPRingBasisBlock",
    "ScaleShiftBlock",
    "LinearDipoleReadoutBlock",
    "NonLinearDipoleReadoutBlock",
    "InteractionBlock",
    "NonLinearReadoutBlock",
    "PolynomialCutoff",
    "BesselBasis",
    "GaussianBasis",
    "MACE",
    "ScaleShiftMACE",
    "BOTNet",
    "ScaleShiftBOTNet",
    "AtomicDipolesMACE",
    "EnergyDipolesMACE",
    "WeightedEnergyForcesLoss",
    "WeightedForcesLoss",
    "WeightedEnergyForcesVirialsLoss",
    "WeightedEnergyForcesStressLoss",
    "DipoleSingleLoss",
    "WeightedEnergyForcesDipoleLoss",
    "WeightedHuberEnergyForcesStressLoss",
    "UniversalLoss",
    "OMat24Loss",
    "DDP_weighted_MAE_all",
    "DDP_weighted_MAE_peratomE",
    "SymmetricContraction",
    "interaction_classes",
    "compute_mean_std_atomic_inter_energy",
    "compute_avg_num_neighbors",
    "compute_statistics",
    "compute_fixed_charge_dipole",
    "EquivariantLowOrderProductBasisBlock",
    "EquivariantProductBasisDensityAttnBlock",
]
