"""Regenerate the committed goldens.

Goldens are edit-locked. Every artifact under ``tests/golden/`` -- the
fixtures, the anchor checkpoints, the reference JSONs -- is only rewritten by
this script, and only in a change that does nothing else and explains the
physics of what moved. That is why it refuses to run without
``--i-know-what-i-am-doing``: a regeneration that happens as a side effect of
a feature change destroys the only evidence that the feature changed nothing
it should not have.

Usage::

    python tests/golden/regenerate.py --target all --i-know-what-i-am-doing

The targets are not listed here. Each family of goldens owns a module in
``tests/golden/targets/`` and declares its own name, its order and its help
line; ``--help`` reads them off the package. ``--target all`` runs the
families that need nothing beyond a plain development environment, in
dependency order, and names the ones it skipped instead of leaving their
references silently stale.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

GOLDEN_ROOT = Path(__file__).resolve().parent
REPO_ROOT = GOLDEN_ROOT.parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# pylint: disable=wrong-import-position
from tests.golden import targets  # noqa: E402


def main(argv=None) -> int:
    available = targets.discover()
    listing = "\n".join(
        f"  {name:22s} {target.help}"
        + ("" if target.in_all else "   (not part of 'all')")
        for name, target in available.items()
    )
    parser = argparse.ArgumentParser(
        description=__doc__,
        epilog=f"targets, in the order 'all' runs them:\n{listing}",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--target",
        choices=["all", *available],
        default="all",
        help="which golden artifacts to rewrite",
    )
    parser.add_argument(
        "--i-know-what-i-am-doing",
        action="store_true",
        help=(
            "required. Regenerating a golden discards the evidence it was "
            "collected to provide; do it in its own reviewed change."
        ),
    )
    args = parser.parse_args(argv)
    if not args.i_know_what_i_am_doing:
        parser.error(
            "refusing to rewrite committed goldens without "
            "--i-know-what-i-am-doing. These files are the reference the "
            "rewrite is measured against; regenerating one turns a failing "
            "test into a passing one without anyone deciding that the new "
            "numbers are correct."
        )

    if args.target == "all":
        selected = [name for name, t in available.items() if t.in_all]
        skipped = [name for name, t in available.items() if not t.in_all]
    else:
        selected, skipped = [args.target], []

    for name in selected:
        print(f"[{name}]")
        available[name].run()

    if skipped:
        print(
            "\nnot regenerated by 'all', ask for each by name once its "
            "requirements are in place:\n  " + "\n  ".join(skipped)
        )
    return 0


if __name__ == "__main__":  # pragma: no cover - manual invocation
    raise SystemExit(main())
