name: unit tests
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8','3.9','3.10','3.11','3.12']

    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install requirements
        run: |
          pip install -U pip
          pip install .[dev]

      - name: Log installed environment
        run: |
          python3 -m pip freeze

      - name: Run unit tests
        run: |
          pytest tests
